### ISSUE TITLE
Eliminate uses of deprecated CONSTANTS

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sync_http#5]
This package still uses deprecated Dart 1 SCREAMING CAPS CONSTANTS. These will be removed shortly in Dart 2. This rewriting tool is available for the migration: This tool is available for the migration: https://github.com/dart-lang/dart2_fix .

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/sync_http/commit/e8bf40c2e1161c5b956b85a1cd87c661cd724201

published as 0.1.2
